[tool.bumpversion]
commit = true
current_version = "0.5.1"
message = 'Bump version: v{new_version}'

[[tool.bumpversion.files]]
filename = "crates/core/Cargo.toml"
search = '''
[package]
name = "core"
version = "{current_version}"
'''
replace = '''
[package]
name = "core"
version = "{new_version}"
'''

[[tool.bumpversion.files]]
filename = 'pyproject.toml'
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = 'calzone_display/__init__.py'
search = 'VERSION = "{current_version}"'
replace = 'VERSION = "{new_version}"'
