name: Package
on:
  workflow_dispatch:
    inputs:
      sdist:
        description: 'Build sdist'
        required: true
        type: boolean
        default: true
      wheel:
        description: 'Build wheel'
        required: true
        type: boolean
        default: true
      upload:
        description: 'Upload to PyPI'
        required: true
        type: boolean
        default: false

env:
  MACOSX_DEPLOYMENT_TARGET: '11.0'

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    if: ${{ inputs.sdist }}
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: dist/*.tar.gz

  build_wheel:
    name: Build wheel (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14, windows-2022, windows-11-arm]
    if: ${{ inputs.wheel }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain (Windows-11/arm64)
        if: ${{ matrix.os == 'windows-11-arm' }}
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build wheel
        uses: pypa/cibuildwheel@v2.23.3  # 2.23.3: supports Python 3.7.

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  upload:
    name: Upload to PyPI
    needs: [build_wheel, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    if: ${{ inputs.upload }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
